vm: Minimize iostream deps for header files.
I ended up with an obscure error message when I removed the iostream
include...

    error: use of enum 'Opcode' without previous declaration
    error: expected unqualified-id before ':' token

.. For this line:

    enum OpCode : int32_t {
        ...
    }

Was caused by a missing definition of int32_t.